### ISSUE TITLE
lunar to solar seems lost 1 day

### ISSUE THREAD

**Issue by kjx98** [nosixtools/solarlunar#1]
2005-02-08 lunar is 2005-01-01 lunar,  LunarToSolar got 2004年12月30日

**Comment by kjx98** [comment]
dayDuaration, _ := time.ParseDuration("24h")
    myDate = myDate.Add(dayDuaration * time.Duration(offset))
    return myDate.Format(DATELAYOUT)
because of leap second, LunarToSolar lost 1 day after 2000-01-01.  Code changed to:
    dayDuaration, _ := time.ParseDuration("24h")
    myDate = myDate.Add(dayDuaration * time.Duration(offset))
    minDuaration, _ := time.ParseDuration("10m")
    myDate = myDate.Add(minDuaration)
    return myDate.Format(DATELAYOUT)

**Comment by kjx98** [comment]
using Parse instead of ParseInLocation also works

**Comment by nosixtools** [comment]
Sorry for a bit late for this, I will deal with this problem right away.

**Comment by nosixtools** [comment]
测试了阳历2005-02-08 对应的是腊月十三 2005-02-09是大年初一 和万年历做了对比 未出现差错
