### ISSUE TITLE
日期计算有点问题

### ISSUE THREAD

**Issue by safehumeng** [nosixtools/solarlunar#2]
举个栗子，关于感恩节（m11w4n5）的计算，不是第4周周4，而是第4个周四，如果第一个周没有周四，就不算第一周

**Comment by safehumeng** [comment]
清明节计算也有点问题，改成day := int(d * 0.2422 + val - d/4) 即计算清明节的时候公式中(yy/4.0)不应该截取整数部分。

**Comment by nosixtools** [comment]
好的 我修复下这个问题
