### ISSUE TITLE
关于新历农历转换的问题

### ISSUE THREAD

**Issue by safehumeng** [nosixtools/solarlunar#3]
solarlunar.go 105行和106行
dayDuaration, _ := time.ParseDuration("24h")
myDate = myDate.Add(dayDuaration * time.Duration(offset))
这个计算时间有问题，应该换成
myDate = myDate.AddDate(0, 0, offset)
如果用上面那个会造成比如
![image](https://user-images.githubusercontent.com/16226299/70291019-d890c400-1814-11ea-9628-a2014fb86127.png)这样的时间

**Comment by nosixtools** [comment]
好的 我修复下这个问题

**Comment by nosixtools** [comment]
问题已修复
