### ISSUE TITLE
compareWeek has some bug?

### ISSUE THREAD

**Issue by RickyWangGithub** [nosixtools/solarlunar#6]
![image](https://user-images.githubusercontent.com/7765174/139235305-822ae4a6-05cc-4f78-b704-c2811c9a05a2.png)
should be as follows: @nosixtools 
![image](https://user-images.githubusercontent.com/7765174/139235427-3b8628b4-9ff4-4681-a98d-5778d0b2deda.png)

which lead to the 2021 Thanks Giving Day get nothing.
`festival := festival.NewFestival("./festival.json");
	fmt.Println(festival.GetFestivals("2021-11-24"))`

**Comment by nosixtools** [comment]
thx, fixed
